#!/bin/bash
clear
echo "-------------------- DuOS Shell --------------------"
uname -a
echo "----------------------- Bash -----------------------"
bash --version || echo "Could fetch Bash version."
echo "----------------------- Wine -----------------------"
wine --version || echo "Could fetch Wine version."
echo "----------------------- Box64 ----------------------"
box64 --version || echo "Could fetch Box64 version."
echo "----------------------- Login ----------------------"
echo "Type 'exit' or [Ctrl] + [D] to exit from DuOS Shell."
bash --login -i
echo "----------------------- Exit -----------------------"
echo "DuOS Shell exited. Goodbye!"
sleep 1
